# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [103]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [104]:
print(np.__version__)
print(np.show_config)

1.26.4
<function show at 0x7c9bcef425f0>


### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```



In [105]:
null_vec=np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [106]:
null_vec=np.zeros(10)
null_vec[4]=1
print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [107]:
vec=np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [108]:
vec=np.arange(0,10)
reverse_vec=vec[::-1]
print(reverse_vec)

[9 8 7 6 5 4 3 2 1 0]


### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [109]:
matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [110]:
list=[1,2,0,0,4,0]
non_zero_element=np.nonzero(list)
print(non_zero_element)

(array([0, 1, 4]),)


### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [111]:
i_matrix=np.eye(3)
print(i_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.07822074 0.76195472 0.95999111]
  [0.69540693 0.16669248 0.97247214]
  [0.7031054  0.38007668 0.61202825]]

 [[0.41082729 0.42783868 0.17188845]
  [0.71563068 0.36917752 0.17016863]
  [0.90248986 0.07040389 0.40558888]]

 [[0.90725777 0.19353039 0.40379553]
  [0.762831   0.70087899 0.09089228]
  [0.68469463 0.17365128 0.17850461]]]
```

In [112]:
randomA=np.random.random((3,3,3))
print(randomA)

[[[0.60662962 0.44915131 0.22535416]
  [0.6701743  0.73576659 0.25799564]
  [0.09554215 0.96090974 0.25176729]]

 [[0.28216512 0.76825393 0.7979234 ]
  [0.5440372  0.38270763 0.38165095]
  [0.28582739 0.74026815 0.23898683]]

 [[0.4377217  0.8835387  0.28928114]
  [0.78450686 0.75895366 0.41778538]
  [0.22576877 0.42009814 0.06436369]]]


### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.009762523436238846 0.9916129188134726
```

In [113]:
randomA=np.random.random((10,10))
print(randomA.min(),randomA.max())

0.01648793481663091 0.9997413066863959


### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.43970256642748734
```

In [114]:
randomV=np.random.random(30)
print(randomV.mean())

0.484312482935278


### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [115]:
array2d=np.zeros((10,10))
array2d[0,:]=1
array2d[-1,:]=1
array2d[:,0]=1
array2d[:,-1]=1
print(array2d)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [116]:
array=np.ones((5,5))
array2=np.zeros((array.shape[0], array.shape[1]))
array2[1:-1,1:-1]=array[1:-1,1:-1]
print(array2)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [117]:
0 * np.nan

nan

nan은 어떤 숫자랑 곱해도 nan이 된다.

In [118]:
np.nan == np.nan

False

nan은 어떤 값과도 같지 않아 nan끼리도 같지 않다.

In [119]:
np.inf > np.nan

False

nan은 숫자가 아니므로 어떤 숫자와 비교해도 거짓이다.

In [120]:
np.nan - np.nan

nan

연산에 nan이 포함되면 결과는 nan이다.

In [121]:
np.nan in set([np.nan])

True

집합에 nan이 포함되어 있으므로 참이다.

In [122]:
0.3 == 3 * 0.1

False

소수점 연산의 정확성 문제로 두개의 값은 미세하게 다를 수 있다.

### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[ 1.57158744 -0.5567505  -1.44275417  0.73527327 -1.17233846]
 [ 0.63460149 -0.73078623 -0.62656662 -1.36290509 -0.44364149]
 [ 0.22741386 -1.10400477  0.86652275 -0.95095209  1.38123574]
 [ 0.1921141  -0.30224638 -1.24440971  0.96181116  0.75106165]
 [-1.43422964  0.67492878  1.48089838  0.53420107  1.35993544]]
```

In [123]:
randomM=np.random.random((5,5))
normalizedM=(randomM-np.mean(randomM))/np.std(randomM)
print(normalizedM)

[[ 5.20669951e-01  8.71375669e-01 -4.87035574e-01  1.12797083e+00
   2.85625601e-01]
 [ 3.77335745e-01 -2.26265145e-02  9.03736740e-01  9.21952703e-01
   1.03193503e+00]
 [-1.93338389e+00  6.47799583e-01  1.29483333e+00 -1.64378047e+00
  -1.58729384e+00]
 [-1.84620818e+00 -9.16169749e-01  6.32632837e-01 -1.48348590e-01
   4.45262936e-01]
 [-1.19920585e+00 -1.92599037e-03  1.11897444e+00  4.40134797e-01
  -8.34261555e-01]]


### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [124]:
A=np.random.random((5,3))
B=np.random.random((3,2))
C=np.dot(A,B)
print(C)

[[1.06586325 0.98028287]
 [1.0252362  1.08551684]
 [1.23680288 1.64152422]
 [1.00088201 0.73765164]
 [1.34564731 1.30592838]]


### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [125]:
np.array(0) / np.array(0)

<ipython-input-125-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

0으로 나눌 수 없으므로 결과는 nan이다.

In [126]:
np.array(0) // np.array(0)

<ipython-input-126-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

수학적으로는 오류가 있지만 넘파이는 0을 반환한다.

In [127]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-127-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

nan을 정수로 변환하면 최대의 음의 정수가 된다.

### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [128]:
matrix= np.array([[j for j in range(5)] for i in range(5)])
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.1738448  0.20689089 0.26989562 0.29896317 0.41140555 0.44166027
 0.48569307 0.78561734 0.79300508 0.95618918]

```

In [129]:
randomV=np.random.random(10)
randomV.sort()
print(randomV)

[0.09589633 0.15224761 0.15997913 0.29213589 0.33767887 0.43598192
 0.75032907 0.80381518 0.86488287 0.94650558]


## **판다스**


### 1. Import pandas under the alias `pd`.

In [130]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [131]:
print(pd.__version__)

2.1.4


## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```


### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.


In [152]:
# 문제 풀이 전 numpy 임포트
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [134]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [135]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [136]:
df[['animal','age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [137]:
df.loc[['c','d','h'],['animal','age']]

animal  age
c  snake  0.5
d    dog  NaN
h    cat  NaN

### 9. Select only the rows where the number of visits is greater than 3.

In [138]:
df[df['visits']>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [139]:
df[df['age'].isna()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [140]:
df[(df['animal']=='cat')&(df['age']<3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).  


In [141]:
df[(df['age'] >= 2) & (df['age'] <= 4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [142]:
df.loc['f', 'age'] = 1.5
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [143]:
df['visits'].sum()

19

### 15. Calculate the mean age for each different animal in `df`.

In [144]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [145]:
new= {'animal': 'dog', 'age': 4, 'visits': 1, 'priority': 'no'}
df.loc['k'] = new
print(df)

df=df.drop('k')
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    dog  4.0       1       no
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 17. Count the number of each type of animal in `df`.

In [146]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [147]:
df.sort_values(by=['age', 'visits'], ascending=[False, True])

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [154]:
df.loc[:, 'priority'] = df['priority'].map({'yes': True, 'no': False})
print(df)

  animal  age  visits priority
a    cat  2.5       1     True
b    cat  3.0       3     True
c  snake  0.5       2    False
d    dog  NaN       3     True
e    dog  5.0       2    False
f    cat  2.0       3    False
g  snake  4.5       1    False
h    cat  NaN       1     True
i    dog  7.0       2    False
j    dog  3.0       1    False


### 20. In the 'animal' column, change the 'snake' entries to 'python'.   

In [155]:
df.loc[:, 'animal'] = df['animal'].replace('snake', 'python')

In [156]:
# 확인용 df 출력 셀
df

animal  age  visits priority
a     cat  2.5       1     True
b     cat  3.0       3     True
c  python  0.5       2    False
d     dog  NaN       3     True
e     dog  5.0       2    False
f     cat  2.0       3    False
g  python  4.5       1    False
h     cat  NaN       1     True
i     dog  7.0       2    False
j     dog  3.0       1    False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [164]:
# 랜덤 시드 고정
np.random.seed(2024)

df = pd.DataFrame(np.random.random(size=(5, 3)))


In [165]:
df2=df.sub(df.mean(axis=1), axis=0)
print(df2)

          0         1         2
0  0.096256  0.207350 -0.303606
1 -0.074488  0.086722 -0.012234
2  0.100411  0.052572 -0.152983
3  0.041629 -0.387560  0.345931
4 -0.140416  0.218913 -0.078496
