# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [ ]:
print(np.__version__)
np.show_config

1.26.4


<function numpy.__config__.show(mode='stdout')>

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```



In [ ]:
zero_array = np.zeros((10,))
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [ ]:
zero_array2 = np.zeros((10,))
zero_array2[4] = 1
print(zero_array2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [ ]:
sequence_array = np.arange(start=10, stop=50)
print(sequence_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [ ]:
array1 = np.arange(10)
reverse_array1 = np.sort(array1)[::-1]
print(reverse_array1)

[9 8 7 6 5 4 3 2 1 0]


### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [ ]:
array2 = np.arange(9)
reshape_array2 = array2.reshape(3,3)
print(reshape_array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [ ]:
array3 = np.array([1, 2, 0, 0, 4, 0])
non_zero = np.nonzero(array3) #np.nonzero() 함수는 0이 아닌 요소의 인덱스 반환
print(non_zero)

(array([0, 1, 4]),)


### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

[ np.eye() ]
- 단위 행렬을 만들기 위해 사용할 수 있음
- 단위 행렬: 주 대각선에 1이 있고 나머지 요소는 0인 정사각형 행렬
- np.eye(n)에서 n은 행렬의 크기
  - np.eye(3) -> 3 * 3 단위행렬 생

In [ ]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.07822074 0.76195472 0.95999111]
  [0.69540693 0.16669248 0.97247214]
  [0.7031054  0.38007668 0.61202825]]

 [[0.41082729 0.42783868 0.17188845]
  [0.71563068 0.36917752 0.17016863]
  [0.90248986 0.07040389 0.40558888]]

 [[0.90725777 0.19353039 0.40379553]
  [0.762831   0.70087899 0.09089228]
  [0.68469463 0.17365128 0.17850461]]]
```

[ np.ranom.rand() 함수 사용 ]
- 이 함수는 주어진 크기의 배열을 생성
- 0과 1 사이의 균일  분포에서 랜덤한 값을 채움

In [ ]:
random_array = np.random.rand(3,3,3)
print(random_array)

[[[0.35678648 0.53208635 0.78278768]
  [0.87349068 0.27206748 0.129415  ]
  [0.66468849 0.50872854 0.82552563]]

 [[0.64002679 0.32400894 0.69935782]
  [0.49130714 0.0165153  0.80204506]
  [0.18950401 0.88033788 0.26745268]]

 [[0.80037536 0.93476488 0.00882379]
  [0.72260539 0.1526766  0.46288842]
  [0.86380704 0.26533191 0.94482813]]]


### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.009762523436238846 0.9916129188134726
```

In [ ]:
random_array2 = np.random.rand(10,10)
print(random_array2.min(),random_array2.max())

0.00426115359001078 0.9980307026889376


### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.43970256642748734
```

In [ ]:
random_vector = np.random.rand(30)
mean_value = random_vector.mean()
print(mean_value)

0.4894800618151263


### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [ ]:
array4 = np.zeros((10,10))

array4[0,:] = 1
array4[:,0] = 1
array4[:,9] = 1
array4[9,:] = 1
print(array4)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [ ]:
print("#before")
array5 = np.ones((5,5))
print(array5)

#before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
print("#after")
array5[0,:]=0
array5[:,0]=0
array5[:,4]=0
array5[4,:]=0
print(array5)

#after
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan) #어떤 수를 곱하든 NaN을 곱하면 결과는 항상 NaN
print(np.nan == np.nan) #NaN은 자기 자신과도 같지 않다고 정의
print(np.inf > np.nan) #무한대는 NaN과 비교할 수 없음
print(np.nan - np.nan) #NaN-NaN은 NaN임
print(np.nan in set([np.nan])) #집합에서 NaN 포함 가능,NaN은 집합 내에서 자기 자신과 같다고 판단
print(0.3 == 3 * 0.1) #부동 소수점 연산의 정확도 문제로 인해 False

nan
False
False
nan
True
False


### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[ 1.57158744 -0.5567505  -1.44275417  0.73527327 -1.17233846]
 [ 0.63460149 -0.73078623 -0.62656662 -1.36290509 -0.44364149]
 [ 0.22741386 -1.10400477  0.86652275 -0.95095209  1.38123574]
 [ 0.1921141  -0.30224638 -1.24440971  0.96181116  0.75106165]
 [-1.43422964  0.67492878  1.48089838  0.53420107  1.35993544]]
```

In [ ]:
random_matrix = np.random.rand(5,5) #5*5 랜덤 행렬
mean = random_matrix.mean()
std = random_matrix.std()
normalized = (random_matrix - mean) / std #정규화
print(normalized)

[[ 0.63012474  0.41496638 -1.11294424  1.00648285  1.02057942]
 [ 1.25720663  1.17492265  0.78428902  0.47215794 -1.02225006]
 [-1.7531689  -0.67958035 -1.36815413 -1.46490963 -0.73034004]
 [ 1.14986575  0.12418174  0.45248925 -1.28208473 -0.75077944]
 [ 1.17568363  0.43080307 -0.4352359   1.38685366 -0.8811593 ]]


### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [ ]:
A = np.ones((5,3))
B = np.ones((3,2))
dot_product = np.dot(A,B)
print(dot_product)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0)) #0으로 나누는 것이 정의 되지 않아서 nan
print(np.array(0) // np.array(0)) #이때도 0으로 나누는 것이 정의 되지 않지만 Numpy가 특정 상황에서 0으 반환하도록 처리
print(np.array([np.nan]).astype(int).astype(float)) #NaN이 정수로 변환될 때 일반적으로 매우 큰 음수로 표현, 다시 부동 소수점으로 변환할 때 이 값이 유지

nan
0
[-9.22337204e+18]


<ipython-input-26-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-26-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-26-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [ ]:
array6 = np.arange(5, dtype='float64')
#np.tile()함수: Numpy에서 배열을 반복하여 새로운 배열을 생성하는 함수
#np.tile(A,reps)-> A:반복할 배열, reps:축마다 반복할 횟수
matrix2 = np.tile(array6,(5,1))
print(matrix2)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.1738448  0.20689089 0.26989562 0.29896317 0.41140555 0.44166027
 0.48569307 0.78561734 0.79300508 0.95618918]

```

In [ ]:
random_vector2 = np.random.rand(10,)
sort_ranvec2 = np.sort(random_vector2)
print(sort_ranvec2)

[0.02996001 0.1343712  0.28469186 0.30006079 0.38986721 0.51581734
 0.57442038 0.7684952  0.82357569 0.9558796 ]


## **판다스**


### 1. Import pandas under the alias `pd`.

In [1]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [2]:
print(pd.__version__)

2.1.4


## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```


In [58]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.


In [59]:
# 문제 풀이 전 numpy 임포트
import numpy as np

df =pd.DataFrame(data, index=labels)
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [40]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [41]:
df.iloc[0:3,:]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [13]:
df.loc[:,['animal','age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [16]:
df.iloc[[2,3,7],[0,1]]

animal  age
c  snake  0.5
d    dog  NaN
h    cat  NaN

### 9. Select only the rows where the number of visits is greater than 3.

In [20]:
greater3 = df['visits'] > 3
df[greater3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [22]:
missing = df['age'].isna()
missing_row = df[missing]
print(missing_row)

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [23]:
df[(df['animal']=='cat') & (df['age']<3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).  


In [25]:
df[(df['age']>=2)&(df['age']<=4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [26]:
df.loc['f','age']=1.5
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [28]:
df['visits'].sum()

19

### 15. Calculate the mean age for each different animal in `df`.

In [42]:
mean_age=df.groupby('animal')['age'].mean()
print(mean_age)

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64


### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [61]:
print("###Append a new row###")
new_row = pd.DataFrame({'animal': ['cat'], 'age': [1], 'visits': [1], 'priority': ['no']}, index=['k'])

df = pd.concat([df, new_row])
print(df)

print("###Delete the row###")
df.drop(['k'],axis=0, inplace=True)
print(df)

###Append a new row###
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    cat  1.0       1       no
###Delete the row###
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 17. Count the number of each type of animal in `df`.

In [64]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [70]:
sort1 = df.sort_values(by=['age','visits'],ascending=[False,True])
sort1

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [71]:
df['priority'] = df['priority'].map({'yes':True,'no':False})
df

animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  2.0       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

### 20. In the 'animal' column, change the 'snake' entries to 'python'.   

In [72]:
#replace() : 특정 값들을 다른 값으로 변경하는 데 사용
df['animal']=df['animal'].replace('snake','python')

In [73]:
# 확인용 df 출력 셀
df

animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  2.0       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [78]:
# 랜덤 시드 고정
np.random.seed(2024)

df = pd.DataFrame(np.random.random(size=(5, 3)))

mean = df.mean(axis=0)
df = df.sub(mean,axis=0)



In [79]:
df

0         1        2
0  0.106053  0.217147 -0.29381
1 -0.469074 -0.307864 -0.40682
2  0.290235  0.242395  0.03684
3       NaN       NaN      NaN
4       NaN       NaN      NaN