넘파이 ndarray 개요

In [ ]:
import numpy as np

In [ ]:
#array(), shape 변수(차원과 크기)활용
array1=np.array([1,2,3])
print('array1 type :', type(array1))
print('array1 array 형태 :', array1.shape)
array2=np.array([[1,2,3],[2,3,4]])
print('array2 type :', type(array2))
print('array2 array 형태 :', array2.shape)
array3=np.array([[1,2,3]])
print('array3 type :', type(array3))
print('array3 array 형태 :', array3.shape)

array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,)
array2 type : <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)
array3 type : <class 'numpy.ndarray'>
array3 array 형태 : (1, 3)


(3,)> 3개의 데이터 but 1차원, (2,3)>2개의 로우,3개의 칼럼,2차원, (1,3)> 1개의 로우 3개의 칼럼, 2차원

In [ ]:
#차원 확인 함수 ndim()
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원, array2:2차원, array3: 2차원


ndarray의 데이터 타입

In [ ]:
#list를 ndarray로 쉽게 변경 가능
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
#ndarray내에 다른 데이터 타입이 존재할 경우 > 데이터의 크기가 더 큰 데이터 타입으로 형 변환
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)
list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
#astpye()을 활용한 데이터의 형변환, 인자로 원하는 데이터 타입을 문자열로
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


ndarray를 편리하게 생성하기
1. arange()

In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


2. zeros(), ones()

In [ ]:
#인자값으로 shape 입력, zeros은 0으로 ones는 1로 채운 ndarray 반환
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2),dtype='int32')
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


ndarray의 차원과 크기를 변경하는 reshape()

In [ ]:
# reshape()
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
# 인자 -1의 활용
array1=np.arange(10)
print(array1)

array2=array1.reshape(-1,5)
print('array2 shape',array2.shape)

array3=array1.reshape(5,-1)
print('array3 shape',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape (2, 5)
array3 shape (5, 2)


In [ ]:
# (-1,1)의 활용 > 항상 2차원이고, 칼럼의 개수가 1개인 ndarray 반환
array1=np.arange(8)
array3d=array1.reshape(2,2,2)
print('array3d:\n',array3d.tolist())
# 3차원 ndarray를 2차원으로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape',array5.shape)
# 1차원을 2차원으로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape (8, 1)


넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱
1. 단일 값 추출

In [ ]:
#단일 값 추출
#array 생성
array1=np.arange(start=1,stop=10)
print('array1 :', array1)
value=array1[2]
print('value : ',value)
print(type(value))

array1 : [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int64'>


In [ ]:
#-는 뒤에서부터 인덱스를 의미
print('맨 뒤의 값 :', array1[-1],', 맨 뒤 두번째의 값 :', array1[-2])

맨 뒤의 값 : 9 , 맨 뒤 두번째의 값 : 8


In [ ]:
#2차원 ndarray에서 단일 값 추출하기=>row와 col위치로 인덱스 접근
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3) #3*3배열
print(array2d)
print('(r=0.c=0)index 가리키는 값 : ',array2d[0,0])
print('(r=0.c=1)index 가리키는 값 : ',array2d[0,1])
print('(r=1.c=0)index 가리키는 값 : ',array2d[1,0])
print('(r=2.c=2)index 가리키는 값 : ',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(r=0.c=0)index 가리키는 값 :  1
(r=0.c=1)index 가리키는 값 :  2
(r=1.c=0)index 가리키는 값 :  4
(r=2.c=2)index 가리키는 값 :  9


2. 슬라이싱

In [ ]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 생략하는 경우
array1=np.arange(start=1,stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#다차원 배열에서 슬라이싱
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d:[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d:[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d:[1:3,:]\n',array2d[1:3,:])
print('array2d:[:,:]\n',array2d[:,:])
print('array2d:[:2,1:]\n',array2d[:2,1:])
print('array2d:[:2,0]\n',array2d[:2,0]) # 단일 축만 사용가능

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d:[0:2,0:2]
 [[1 2]
 [4 5]]
array2d:[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d:[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d:[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d:[:2,1:]
 [[2 3]
 [5 6]]
array2d:[:2,0]
 [1 4]


3. 팬시 인덱싱

In [ ]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>',array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


4. 불린 인덱싱

In [ ]:
# []안에 조건문 기재
array1d=np.arange(start=1,stop=10)
array3=array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과값 : ', array3)

array1d > 5 불린 인덱싱 결과값 :  [6 7 8 9]


In [ ]:
# 조건식을 할당하면 각 값마다 T/F값을 ndarray객체로 반환해준다
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


행렬의 정렬 - sort()와 argsort()
1. 행렬 정렬

In [ ]:
org_array=np.array([3,1,9,5])
print('원본 :',org_array)
#np.sort() > 원 행렬은 유지
sort_array1=np.sort(org_array)
print('np.sort()호출 후 반환된 정렬 행렬 :',sort_array1)
print('np.sort()호출 후 원본 행렬 :',org_array)
#ndarray.sort()> 원 행렬 자체를 정렬하여 반환
sort_array2=org_array.sort()
print('org_array.sort()호출 후 반환된 정렬 행렬 :',sort_array2) #none
print('org_array.sort()호출 후 원본 행렬 :',org_array)

원본 : [3 1 9 5]
np.sort()호출 후 반환된 정렬 행렬 : [1 3 5 9]
np.sort()호출 후 원본 행렬 : [3 1 9 5]
org_array.sort()호출 후 반환된 정렬 행렬 : None
org_array.sort()호출 후 원본 행렬 : [1 3 5 9]


In [ ]:
#내림차순도 가능
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬 :',sort_array1_desc)

내림차순으로 정렬 : [9 5 3 1]


In [ ]:
#2차원 이상의 행렬 > axis 축 값 기준으로
array2d=np.array([[8,12],[7,1]])
s_a2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬 :\n',s_a2d_axis0)
s_a2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬 :\n',s_a2d_axis1)

로우 방향으로 정렬 :
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 :
 [[ 8 12]
 [ 1  7]]


2. 정렬된 행렬의 인덱스 반환

In [ ]:
#원본 행렬 정렬 시 행렬 인덱스 값
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('원본 행렬 정렬 시 행렬 인덱스:', sort_indices)

<class 'numpy.ndarray'>
원본 행렬 정렬 시 행렬 인덱스: [1 0 3 2]


In [ ]:
#메타 데이터를 표시하는 별도의 ndarray표기하기
import numpy as np
name_array=np.array(['A','B','C','D','E'])
score_array=np.array([12,3,41,17,6])
sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬시 score_array의 인덱스 :',sort_indices_asc )
print('성적 오름차순으로 name_array의 이름 출력 :',name_array[sort_indices_asc])

성적 오름차순 정렬시 score_array의 인덱스 : [1 4 0 3 2]
성적 오름차순으로 name_array의 이름 출력 : ['B' 'E' 'A' 'D' 'C']


선형대수의 연산
1. 행렬 내적

In [ ]:
# 행렬 내적
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print('행렬 내적의 결과:\n',dot_product)

행렬 내적의 결과:
 [[ 58  64]
 [139 154]]


2. 전치 행렬

In [ ]:
# 전치 행렬
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬:\n',transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]


데이터 핸들링 - 판다스

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
import pandas as pd
titanic_df=pd.read_csv(r'/content/drive/MyDrive/titanic/train.csv')
titanic_df.head(3)
print('DataFrame 크기 :', titanic_df.shape)

DataFrame 크기 : (891, 12)


In [9]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [10]:
#value_counts() : 해당 칼럼값의 유형과 건수를 반환
value_counts=titanic_df['Pclass'].value_counts()
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64


In [11]:
# 해당 칼럼에 해당하는 Series 객체를 반환
titanic_pclass=titanic_df['Pclass']
print(type(titanic_pclass))
# 반환된 Series 객체 확인해보기
titanic_pclass.head()

<class 'pandas.core.series.Series'>


0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

1. ''>DataFrame

In [15]:
# 1차원 리스트, 넘파이 ndarray > DataFrame
import pandas as pd
import numpy as np

col_name1=['col1']
list1=[1,2,3]
array1=np.array(list1)
print('array1 shape :', array1.shape)
# 리스트를 이용해 DataFrame 생성
df_list1=pd.DataFrame(list1,columns=col_name1)
print('1차원 리스트로 만든 DataFrame :\n',df_list1)
# 넘파이 ndarray를 이용해 DataFrame 생성
df_array1=pd.DataFrame(array1,columns=col_name1)
print('1차원 ndarray로 만든 DataFrame :\n',df_array1)

array1 shape : (3,)
1차원 리스트로 만든 DataFrame :
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame :
    col1
0     1
1     2
2     3


In [17]:
# 2차원 리스트, 넘파이 ndarray > DataFrame // 2*3 > 칼럼명 3개 필요
col_name2=['col1','col2','col3']
list2=[[1,2,3],[4,5,6]]
array2=np.array(list2)
print('array2 shape :', array2.shape)
df_list2=pd.DataFrame(list2,columns=col_name2)
print('2차원 리스트로 만든 DataFrame :\n',df_list2)
df_array2=pd.DataFrame(array2,columns=col_name2)
print('2차원 ndarray로 만든 DataFrame :\n',df_array2)

array2 shape : (2, 3)
2차원 리스트로 만든 DataFrame :
    col1  col2  col3
0     1     2     3
1     4     5     6
2차원 ndarray로 만든 DataFrame :
    col1  col2  col3
0     1     2     3
1     4     5     6


In [18]:
# 딕셔너리 > DataFrame / keys > col명, val > col 데이터
dict={'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict=pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame :\n',df_dict)


딕셔너리로 만든 DataFrame :
    col1  col2  col3
0     1     2     3
1    11    22    33


2. DataFrame>>''

In [20]:
# DataFrame > ndarray
array3=df_dict.values
print('df_dict.values 타입 :',type(array3),'df_dict.values shape:',array3.shape)
print(array3)

df_dict.values 타입 : <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [21]:
# DataFrame > list
list3=df_dict.values.tolist()
print('df_dict.values.tolist() 타입 :',type(list3))
print(list3)
# DataFrame > Dict
dict3=df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입 :',type(dict3))
print(dict3)

df_dict.values.tolist() 타입 : <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입 : <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


DataFrame의 칼럼 데이터 세트 생성과 수정
1. 데이터 세트의 생성

In [23]:
# 일괄적인 값 할당
titanic_df['Age_0']=0
titanic_df.head(3)
# 기존의 Series의 데이터 활용
titanic_df['Age_by_10']=titanic_df['Age']*10 # 각 Age의 데이터 값 10배곱
titanic_df['Fam_No']=titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Fam_No  
0      0         A/5 21171   7.2500   NaN        S      0      220.0       2  
1      0          PC 17599  71.2833   C85        C      0      380.0       2  
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0       1

2. 데이터 세트의 수정

In [24]:
# 기존 칼럼값 업데이트 ㄱㄴ
titanic_df['Age_by_10']=titanic_df['Age_by_10']+100
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Fam_No  
0      0         A/5 21171   7.2500   NaN        S      0      320.0       2  
1      0          PC 17599  71.2833   C85        C      0      480.0       2  
2      0  STON/O2. 3101282   7.9250   NaN        S      0      360.0       1

DataFrame 데이터 삭제

In [25]:
#axis=1 삭제
#새롭게 추가된 Age_0 칼럼 삭제
titanic_drop_df=titanic_df.drop('Age_0',axis=1) #lables은 Age_0
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Fam_No  
0      0         A/5 21171   7.2500   NaN        S      320.0       2  
1      0          PC 17599  71.2833   C85        C      480.0       2  
2      0  STON/O2. 3101282   7.9250   NaN        S      360.0       1

In [28]:
drop_result=titanic_df.drop(['Age_0','Age_by_10','Fam_No'],axis=1, inplace=True)
print('inplace=True 이후 반환된 값:',drop_result)
titanic_df.head(3)

inplace=True 이후 반환된 값: None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [29]:
#axis=0 삭제
pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)
print('####before drop####')
print(titanic_df.head(3))

titanic_df.drop([0,1,2],axis=0,inplace=True)
print('####after drop####')
print(titanic_df.head(3))

####before drop####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
####after drop####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


Index 객체

In [31]:
# 원본 파일 재로딩
titanic_df=pd.read_csv(r'/content/drive/MyDrive/titanic/train.csv')
# Index 객체 추출
indexes=titanic_df.index
# Index 객체 실제 값 array로 변환
print('Index 객체 array 값', indexes.values)

Index 객체 array 값 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 2

In [32]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
6


In [33]:
titanic_reset_df=titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

데이터 셀렉션 및 필터링

In [34]:
print('단일 칼럼 데이터 추출 :\n', titanic_df['Pclass'].head(3))
print('여러개 칼럼 데이터 추출 :\n', titanic_df[['Survived','Pclass']].head(3))

단일 칼럼 데이터 추출 :
 0    3
1    1
2    3
Name: Pclass, dtype: int64
여러개 칼럼 데이터 추출 :
    Survived  Pclass
0         0       3
1         1       1
2         1       3


In [37]:
# 인덱스 변환 가능 표현식 > 슬라이싱, 불린 인덱싱
titanic_df[0:2]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

In [38]:
titanic_df[titanic_df['Pclass']==3].head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

정렬, Aggregation 함수, GroupBy 적용

1. 정렬

In [39]:
titanic_sorted=titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

2. Aggregation 함수 적용

In [40]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [41]:
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

3. GroupBy() 적용

In [43]:
# 파라미터 by에 칼럼명 입력
titanic_groupby=titanic_df.groupby(by='Pclass')
# 또 다른 형태의 DFGroupby가 호출되는 거
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


결손 데이터 처리하기

In [45]:
# isna()로 결손 여부 확인
titanic_df.isna().head(3)
# sum() 호출해서 T는 1로 F는 0으로 변환 > 결손 데이터 개수 구하기 ㄱㄴ
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [46]:
# fillna()로 결손 데이터 처리
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

apply lambda 식으로 데이터 가공

In [47]:
# lambda 식의 예시
a=[1,2,3]
s=map(lambda x:x**2,a)
list(s)

[1, 4, 9]

In [48]:
# Name 칼럼의 문자열 개수를 나타내는 칼럼 Name_len에 생성
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x:len(x))
titanic_df[['Name','Name_len']].head(3)

Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22