# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [5]:
print(np.__version__)
print(np.show_config)


1.26.4
<function show at 0x10421ac00>


### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```



In [7]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [9]:
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [15]:
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [21]:
x=np.arange(0,10)
print(np.flip(x))

[9 8 7 6 5 4 3 2 1 0]


### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [23]:
ar1=np.arange(0,9)
ar2=ar1.reshape(3,3)
print(ar2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [25]:
a=np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4]),)


### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [27]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.07822074 0.76195472 0.95999111]
  [0.69540693 0.16669248 0.97247214]
  [0.7031054  0.38007668 0.61202825]]

 [[0.41082729 0.42783868 0.17188845]
  [0.71563068 0.36917752 0.17016863]
  [0.90248986 0.07040389 0.40558888]]

 [[0.90725777 0.19353039 0.40379553]
  [0.762831   0.70087899 0.09089228]
  [0.68469463 0.17365128 0.17850461]]]
```

In [33]:
ar_rand = np.random.randn(3,3,3)
print(ar_rand)

[[[ 0.76914747  0.61144335 -0.65477999]
  [ 1.22313321 -0.02336936  0.60195362]
  [-1.28624018  0.47421675  0.59865626]]

 [[ 0.46623597  1.53255284  0.07861738]
  [ 1.13132044  1.66308595 -0.10640485]
  [-0.12428144 -0.7765752  -0.03365316]]

 [[ 0.81673685 -0.07453231  0.62982054]
  [-0.76281439 -0.66558904 -0.15575494]
  [-0.75735069 -0.58237448 -1.90572516]]]


### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.009762523436238846 0.9916129188134726
```

In [49]:
random_array = np.random.random((10, 10))

# 최소값과 최대값 찾기
min_value = random_array.min()
max_value = random_array.max()

# 결과 출력
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Minimum Value: 0.0012022392074141353
Maximum Value: 0.9937820754672998


### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.43970256642748734
```

In [51]:
ar1=np.random.random(30)
num=ar1.mean()
print(num)

0.500897667795011


### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [53]:
array_2d=np.ones((10,10))
array_2d[1:-1,1:-1]=0
print(array_2d)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [91]:
array_2d=np.ones((5,5))
print("#before\n",array_2d)

#before
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [93]:
array_2d[[0,-1]]=0
array_2d[0:-1,[0,-1]]=0
print("#after\n",array_2d)

#after
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [109]:
print(0 * np.nan) #np.nan은 숫자가 아니기에 이를 포함하는 모든 연산결과는 nan임
print(np.nan == np.nan) #nan은 nan과 같지 않기에 false
print(np.inf > np.nan) #np.nan은 다른 수와 순서를 갖지 않기에 비교를 할 수 없어 false임
print(np.nan - np.nan) #np.nan은 숫자가 아니기에 이를 포함하는 모든 연산결과는 nan임
print(np.nan in set([np.nan])) #nna은 집합 안에 있을 때 자기 자신과 같다고 간주하기에 true
print(0.3 == 3 * 0.1) #파이썬의 부동 소수점 연산의 특징> 3*0.1은 0.3의 근삿값을 컴퓨터가 저장하므로 false

nan
False
False
nan
True
False


### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[ 1.57158744 -0.5567505  -1.44275417  0.73527327 -1.17233846]
 [ 0.63460149 -0.73078623 -0.62656662 -1.36290509 -0.44364149]
 [ 0.22741386 -1.10400477  0.86652275 -0.95095209  1.38123574]
 [ 0.1921141  -0.30224638 -1.24440971  0.96181116  0.75106165]
 [-1.43422964  0.67492878  1.48089838  0.53420107  1.35993544]]
```

In [117]:
#z점수 공식 = (데이터-데이터의 평균)/데이터의 표준편차
ran_matrix=np.random.random((5,5))
ran_mean=np.mean(ran_matrix)
ran_std=np.std(ran_matrix)
normed_matrix=(ran_matrix-ran_mean)/ran_std
print(normed_matrix)

[[ 1.6365804  -0.78495219 -0.28040031 -1.02942797  1.43434745]
 [-1.30558856  0.58395418  1.26261761  1.20994267  0.33551885]
 [ 1.4576026  -0.00363205  0.75381784  0.55643327 -1.59082124]
 [-0.97737136 -0.38857923  0.36762946 -0.53444049 -0.52216966]
 [ 0.33455482 -1.44675407  1.05441435 -1.50300615 -0.62027022]]


### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [119]:
A=np.random.random((5,3))
B=np.random.random((3,2))
mul_matrix=np.dot(A,B)
print(mul_matrix)

[[0.91141865 0.44351352]
 [0.48407686 0.28875017]
 [0.46589946 0.28297299]
 [0.7755308  0.49283207]
 [0.52439638 0.17237073]]


### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
이거 3번 헷갈림

In [133]:
print(np.array(0) / np.array(0)) 
#np.array(0)가 numpy배열로 0을 포함하는 스칼라배열(단일값 but 배열처럼 다룰 수 있음)
#0/0이므로 정의되지 않은 연산으로 nan을 반환함
print(np.array(0) // np.array(0))
#몫을 반환하는 연산자 //, 이 경우 0나누기 0은 정의되지 않지만 numpy이므로 몫으로 0을 반환 
print(np.array([np.nan]).astype(int).astype(float))
#..?

nan
0
[0.]


/var/folders/2c/j3wmswps2r5gclvj1skrczqh0000gn/T/ipykernel_11986/3753971449.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/2c/j3wmswps2r5gclvj1skrczqh0000gn/T/ipykernel_11986/3753971449.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/2c/j3wmswps2r5gclvj1skrczqh0000gn/T/ipykernel_11986/3753971449.py:6: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [143]:
#0-4값의 1차원 배열을 세로로 5번, 가로로 1번만 쌓아서 5by5행렬 만들기
matrix = np.tile(np.arange(5),(5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.1738448  0.20689089 0.26989562 0.29896317 0.41140555 0.44166027
 0.48569307 0.78561734 0.79300508 0.95618918]

```

In [97]:
v10=np.random.random(10)
v10.sort()
print(v10)

[0.02681636 0.10799395 0.28950143 0.32630225 0.36443307 0.48600552
 0.74339916 0.95306367 0.96811645 0.97362463]


## **판다스**


### 1. Import pandas under the alias `pd`.

In [145]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [147]:
print(pd.__version__)

2.2.2


## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```


### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.


In [187]:
# 문제 풀이 전 numpy 임포트
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(data,index=labels)

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [165]:
print(df.info())


<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None


### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [167]:
print(df.describe())

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000


### 6. Return the first 3 rows of the DataFrame `df`.

In [169]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [171]:
df[['animal','age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [175]:
df.loc[['d','e','i'],['animal', 'age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [189]:
greater_df=df[df['visits']>3]
print(greater_df)

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []


### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [207]:
miss_df=df[df['age'].isna()]
print(miss_df)

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [213]:
catage_df=df[(df['animal']=='cat')&(df['age']<3)]
print(catage_df)

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no


### 12. Select the rows the age is between 2 and 4 (inclusive).  


In [215]:
age_df=df[(df['age']>=2)&(df['age']<=4)]
print(age_df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no


### 13. Change the age in row 'f' to 1.5.

In [217]:
df.loc['f','age']=1.5
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [219]:
total=df['visits'].sum()
print(f"총 방문수 : {total}")

총 방문수 : 19


### 15. Calculate the mean age for each different animal in `df`.

In [221]:
print(df.groupby('animal')['age'].mean())

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64


### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [223]:
df.loc['k']=['cat',3.5,2,'yes']
print(df)
df.drop('k',axis=0,inplace=True) #inplace=True>자신의 df의 데이터 삭제
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    cat  3.5       2      yes
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


### 17. Count the number of each type of animal in `df`.

In [225]:
v_count=df['animal'].value_counts()
print(v_count)

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64


### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [231]:
#by=해당 칼럼으로 작업 수행, ascending=각각 칼럼을 오름차순 내림차순으로 작업할지 f/t로 표현
df_sorted=df.sort_values(by=['age','visits'],ascending=[False,True])
print(df_sorted)
                         

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes


### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [235]:
df['priority']=df['priority'].map({'yes':True,'no':False})
print(df)

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False


### 20. In the 'animal' column, change the 'snake' entries to 'python'.   

In [239]:
df['animal']=df['animal'].replace('snake','python')

In [241]:
# 확인용 df 출력 셀
df

animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [243]:
# 랜덤 시드 고정
np.random.seed(2024)

df = pd.DataFrame(np.random.random(size=(5, 3)))




In [249]:
print("원본데이터\n",df)
subtract_df=df.sub(df.mean(axis=1),axis=0)
print("뺀 데이터\n",subtract_df)

원본데이터
           0         1         2
0  0.588015  0.699109  0.188152
1  0.043809  0.205019  0.106063
2  0.727240  0.679401  0.473846
3  0.448296  0.019107  0.752598
4  0.602449  0.961778  0.664369
뺀 데이터
           0         1         2
0  0.096256  0.207350 -0.303606
1 -0.074488  0.086722 -0.012234
2  0.100411  0.052572 -0.152983
3  0.041629 -0.387560  0.345931
4 -0.140416  0.218913 -0.078496
