# **1주차 복습과제**
- 1주차 복습과제는 **넘파이/판다스 연습문제**입니다.
- 코드 작성하시고, 출력 결과까지 나오도록 실행 부탁드립니다.
  - 제출 시 파일명 본인 이름으로 변경해 주세요. ex) Week1_복습과제_OOO
- 교재에서 다루지 않은 메소드도 다수 포함되어 있지만 구글링이나 챗지피티 등을 활용해서라도 풀어주세요! 한 번씩 사용해 보면 좋을 것 같아 어려워도 문제에 포함했습니다 🤗

## **넘파이**

### 1. Import the numpy package under the name `np`.

In [62]:
import numpy as np

### 2. Print the numpy version and the configuration.

(hint: `np.__version__`, `np.show_config`)

In [63]:
print(np.__version__)
np.show_config

1.26.4


<function numpy.__config__.show(mode='stdout')>

### 3. Create a null vector of size 10.

#### ✅ 출력 예시


```
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
```



In [64]:
list=np.zeros(10)
print(list)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Create a null vector of size 10 but the fifth value which is 1.

#### ✅출력 예시


```
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
```

In [65]:
list=np.zeros(10)
list[4]=1
print(list)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create a vector with values ranging from 10 to 49.

#### ✅출력 예시


```
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
```

In [66]:
list=np.arange(10,50)
print(list)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 6. Reverse a vector (first element becomes last).

#### ✅출력 예시


```
[9 8 7 6 5 4 3 2 1 0]
```

In [67]:
list=np.arange(0,10)
reversed_list=list[::-1]
print(reversed_list)


[9 8 7 6 5 4 3 2 1 0]


### 7. Create a 3x3 matrix with values ranging from 0 to 8.

#### ✅출력 예시


```
[[0 1 2]
 [3 4 5]
 [6 7 8]]
```

In [68]:
list=np.arange(0,9)
reshape_list=list.reshape(3,3)
print(reshape_list)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 8. Find indices of non-zero elements from [1,2,0,0,4,0].

#### ✅출력 예시


```
(array([0, 1, 4]),)
```

In [69]:
list=np.array([1,2,0,0,4,0])
list_non=np.where(list!=0)
list_non

(array([0, 1, 4]),)

### 9. Create a 3x3 identity matrix.

(hint: `np.eye`)

#### ✅출력 예시


```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In [70]:
array=np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 10. Create a 3x3x3 array with random values.

#### ✅출력 예시


```
[[[0.07822074 0.76195472 0.95999111]
  [0.69540693 0.16669248 0.97247214]
  [0.7031054  0.38007668 0.61202825]]

 [[0.41082729 0.42783868 0.17188845]
  [0.71563068 0.36917752 0.17016863]
  [0.90248986 0.07040389 0.40558888]]

 [[0.90725777 0.19353039 0.40379553]
  [0.762831   0.70087899 0.09089228]
  [0.68469463 0.17365128 0.17850461]]]
```

In [71]:
array=np.random.random((3,3,3))
print(array)

[[[0.88019668 0.06957313 0.62694578]
  [0.90598644 0.30876653 0.0990444 ]
  [0.45548291 0.77382444 0.78822988]]

 [[0.17824976 0.81957821 0.5649161 ]
  [0.54716658 0.11278714 0.59834026]
  [0.29994838 0.0104637  0.7795091 ]]

 [[0.61840181 0.06411875 0.58682605]
  [0.31965857 0.5060713  0.78409742]
  [0.15185199 0.43208776 0.67844045]]]


### 11. Create a 10x10 array with random values and find the minimum and maximum values.

#### ✅출력 예시


```
0.009762523436238846 0.9916129188134726
```

In [72]:
array=np.random.random((10,10))
min_value=np.min(array)
max_value=np.max(array)
print(min_value, max_value)

0.0035321372290633146 0.9914958269114098


### 12. Create a random vector of size 30 and find the mean value.

#### ✅출력 예시


```
0.43970256642748734
```

In [73]:
array=np.random.random((30))
mean_value=np.mean(array)
print(mean_value)

0.5157558008828967


### 13. Create a 2d array with 1 on the border and 0 inside. (size: 10x10)

#### ✅출력 예시


```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [74]:
array=np.zeros((10,10))
array[0,:]=1
array[-1,:]=1
array[:,0]=1
array[:,-1]=1
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 14. How to add a border (filled with 0's) around an existing array?

(hint: 인덱싱 사용)

#### ✅출력 예시


```
# before
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 # after
 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

```

In [75]:
array=np.ones((5,5))
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [76]:
array[0,:]=0
array[-1,:]=0
array[:,0]=0
array[:,-1]=0
print(array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 15. What is the result of the following expression?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [77]:
print(0 * np.nan) #0과 nan(없음)을 곱하면 nan임
print(np.nan == np.nan) #nan은 자신과 같지 않으므로 False
print(np.inf > np.nan) #nan과 관련된 비교는 모두 False (inf: 무한대)
print(np.nan - np.nan) #nan에서 nan을 빼면 정의되지 않음. 그러므로 nan
print(np.nan in set([np.nan])) #nan은 nan을 포함하는 집합의 요소가 맞음. 그러므로 True
print(0.3 == 3 * 0.1) #컴퓨터는 이진수로 계산하기 때문에 부동소수점 연산의 경우 오차가 발생함. 그러므로 False

nan
False
False
nan
True
False


### 16. Normalize a 5x5 random matrix.

(hint: (x - mean) / std)

#### ✅출력 예시


```
[[ 1.57158744 -0.5567505  -1.44275417  0.73527327 -1.17233846]
 [ 0.63460149 -0.73078623 -0.62656662 -1.36290509 -0.44364149]
 [ 0.22741386 -1.10400477  0.86652275 -0.95095209  1.38123574]
 [ 0.1921141  -0.30224638 -1.24440971  0.96181116  0.75106165]
 [-1.43422964  0.67492878  1.48089838  0.53420107  1.35993544]]
```

In [78]:
array=np.random.random((5,5))
mean_value=np.mean(array)
std_value=np.std(array)
normalize_array=(array-mean_value)/std_value
print(normalize_array)

[[-0.33101059 -2.148205    0.62572042 -1.10709437 -0.36880613]
 [ 1.60856342  0.06706246 -1.19513096  0.89733297  0.43341455]
 [ 1.05714313  1.14120156 -0.49261973 -1.39239812 -0.60973818]
 [ 1.04945811  1.24830936  0.86062727  0.26294728 -0.89423764]
 [-1.14605238 -0.51005298 -0.44412579  1.56939051 -0.18169916]]


### 17. Multiply a 5x3 matrix by a 3x2 matrix. (real matrix product)

#### ✅출력 예시


```
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
```

In [79]:
array1=np.full((5,3),3)
array2=np.full((3,2),3)
result=np.dot(array1,array2)
print(result)

[[27 27]
 [27 27]
 [27 27]
 [27 27]
 [27 27]]


### 18. What are the result of the following expressions?

(실행 후, 결과에 대한 주석 작성해주세요. ex. 출력 결과에 대한 이유)

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [80]:
print(np.array(0) / np.array(0)) #분모가 0인 경우는 존재할 수 없으므로 nan
print(np.array(0) // np.array(0)) #0d을 0으로 나눈경우의 몫은 0임
print(np.array([np.nan]).astype(int).astype(float))#nan은 정수로 변환 할 수 없으므로 최솟값인-2,147,483,648로 변환후 부동소수점을 적용하면 [-2.14748365e+09]이렇게 출력된다

nan
0
[-9.22337204e+18]


<ipython-input-80-67d59dd116e5>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0)) #분모가 0인 경우는 존재할 수 없으므로 nan
<ipython-input-80-67d59dd116e5>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) #0d을 0으로 나눈경우의 몫은 0임
<ipython-input-80-67d59dd116e5>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))#nan은 정수로 변환 할 수 없으므로 최솟값인-2,147,483,648로 변환후 부동소수점을 적용하면 [-2.14748365e+09]이렇게 출력된다


### 19. Create a 5x5 matrix with row values ranging from 0 to 4.

#### ✅ 출력 예시

```
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
```

In [81]:
row_value=np.arange(0,5)
array=np.tile(row_value,(5,1))
print(array)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 20. Create a random vector of size 10 and sort it.

#### ✅출력 예시


```
[0.1738448  0.20689089 0.26989562 0.29896317 0.41140555 0.44166027
 0.48569307 0.78561734 0.79300508 0.95618918]

```

In [82]:
array=np.random.random(10)
print(np.sort(array))

[0.00526139 0.19887312 0.24150225 0.28189721 0.33568156 0.33854276
 0.40190771 0.48868637 0.50214347 0.69612176]


## **판다스**


### 1. Import pandas under the alias `pd`.

In [83]:
import pandas as pd

### 2. Print the version of pandas that has been imported.

In [84]:
print(pd.__version__)

2.1.4


## 3~20번 문제는 아래 데이터프레임으로 진행됩니다.

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```


### 3. Create a DataFrame `df` from this dictionary `data` which has the index `labels`.


In [85]:
# 문제 풀이 전 numpy 임포트
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

### 4. Display a summary of the basic information about this DataFrame and its data.  
(hint: there is a single method that can be called on the DataFrame)

In [86]:
df=pd.DataFrame(data,index=labels)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


### 5. Display a summary of the basic statistics about data of this DataFrame.  
(hint: there is a single method that can be called on the DataFrame)

In [87]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

### 6. Return the first 3 rows of the DataFrame `df`.

In [88]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

### 7. Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [89]:
df_ani_age=df[['animal','age']]
df_ani_age

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

### 8. Select the data in rows `[3, 4, 8]` **and** in columns `['animal', 'age']`.

In [90]:
df_ani_age.loc[df.index[[3, 4, 8]]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

### 9. Select only the rows where the number of visits is greater than 3.

In [91]:
df[df['visits']>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

### 10. Select the rows where the age is missing, i.e. it is `NaN`.

In [92]:
df[df['age'].isna()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

### 11. Select the rows where the animal is a cat *and* the age is less than 3.

In [93]:
df[(df['animal']=='cat')&(df['age']<3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

### 12. Select the rows the age is between 2 and 4 (inclusive).  


In [94]:
df[(df['age']>=2)&(df['age']<=4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

### 13. Change the age in row 'f' to 1.5.

In [95]:
df.at['f','age']=1.5
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 14. Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [96]:
total_visits=df['visits'].sum()
total_visits

19

### 15. Calculate the mean age for each different animal in `df`.

In [97]:
mean_age_df=df.groupby('animal')['age'].mean()
mean_age_df

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

### 16. Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [98]:
df.loc['k']=['cat',5,3,'yes']
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    cat  5.0       3      yes

In [99]:
df=df.drop('k')
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

### 17. Count the number of each type of animal in `df`.

In [100]:
animal_count=df['animal'].value_counts()
animal_count

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

### 18. Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).
#### ✅출력 예시

 index |animal	| age	|visits|	priority
---|---|---|---|---
i|	dog|	7.0|	2|	no
e|	dog|	5.0|	2|	no
g|	snake|	4.5|	1|	no
j|	dog|	3.0|	1|	no
b|	cat|	3.0|	3|	yes
a|	cat|	2.5|	1|	yes
f|	cat|	1.5|	3|	no
c|	snake|	0.5|	2|	no
h|	cat|	NaN|	1|	yes
d|	dog|	NaN|	3|	yes

In [101]:
df_sort=df.sort_values(by=['age','visits'],ascending=[False,True])
df_sort

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

### 19. The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.  
(hint: `map`)

In [102]:
df['priority']=df['priority'].map({'yes':True, 'no':False})
df

animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

### 20. In the 'animal' column, change the 'snake' entries to 'python'.   

In [103]:
df['animal']=df['animal'].replace({'snake','python'})

<ipython-input-103-0cce764463ba>:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df['animal']=df['animal'].replace({'snake','python'})


In [104]:
# 확인용 df 출력 셀
df

animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

### 21. Given a DataFrame of random numeric values:
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # this is a 5x3 DataFrame of float values
```

how do you subtract the row mean from each element in the row?

In [106]:
# 랜덤 시드 고정
np.random.seed(2024)

df = pd.DataFrame(np.random.random(size=(5, 3)))




In [107]:
df=df.sub(df.mean(axis=1),axis=0)
df

0         1         2
0  0.096256  0.207350 -0.303606
1 -0.074488  0.086722 -0.012234
2  0.100411  0.052572 -0.152983
3  0.041629 -0.387560  0.345931
4 -0.140416  0.218913 -0.078496